version: "3"

networks:
    laravel:

services:

    php:
        image: ftdocker:0.1
        build:
          context: "docker/"
          dockerfile: Dockerfile
        environment:
            - DB_NAME="${DB_NAME}"
            - DB_USER="${DB_USER}"
            - DB_PASS="${DB_PASS}"
            - LARAVEL_KEY="${LARAVEL_KEY}"
            - APACHE_RUN_USER=#1000
            - APACHE_RUN_GROUP=#1000
        container_name: php
        volumes:
            - ./src:/var/www/html
        ports:
            - "9001:80"
        networks:
         - laravel

    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "4307:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USER}"
            MYSQL_PASSWORD: "${DB_PASS}" 
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
         - laravel

    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel

    npm:
        image: node:14.15.3
        container_name: npm
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']
        networks:
            - laravel

    artisan:
        image: ftdocker:0.1
        build:
            context: "docker/"
            dockerfile: Dockerfile
        container_name: artisan
        environment:
            DB_NAME: "${DB_NAME}"
            DB_USER: "${DB_USER}"
            DB_PASS: "${DB_PASS}"
        volumes:
            - ./src:/var/www/html
        depends_on:
            - mysql
        working_dir: /var/www/html
        entrypoint: ['/var/www/html/artisan']
        networks:
            - laravel
